name: dart_and_flutter_examples_app
description: "A set of Dart and Flutter examples for my Individual Development Program (IDP)."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  collection: 1.18.0
  drift: 2.16.0
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: 2.4.10
  go_router: 13.2.0
  http: 1.2.1
  path: 1.9.0
  path_provider: 2.1.2
  riverpod_annotation: 2.3.4
  sqlite3: 2.4.0
  sqlite3_flutter_libs: 0.5.20

dev_dependencies:
  build_runner: 2.4.8
  drift_dev: 2.16.0
  flutter_lints: 3.0.1
  flutter_test:
    sdk: flutter
  mjk_lint_rules: 3.0.1
  riverpod_generator: 2.3.11
  riverpod_lint: 2.3.9

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/images/

# RPS
scripts:
  test: flutter test lib
  build: flutter pub run build_runner build --delete-conflicting-outputs
  watch: flutter pub run build_runner watch
