name: dart_and_flutter_examples_app
description: "A set of Dart and Flutter examples for my Individual Development Program (IDP)."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.6.0
  flutter: ^3.27.0

dependencies:
  collection: any
  drift: 2.22.1
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: 2.6.1
  go_router: 14.6.2
  http: 1.2.2
  intl: 0.19.0
  introduction_screen: 3.1.14
  mds_stopwatch:
    path: ./plugins/mds_stopwatch
  path: 1.9.0
  path_provider: 2.1.5
  riverpod_annotation: 2.6.1
  spider: 4.2.2
  sqlite3: 2.5.0
  sqlite3_flutter_libs: 0.5.28

dev_dependencies:
  build_runner: 2.4.14
  drift_dev: 2.22.1
  flutter_lints: 5.0.0
  flutter_test:
    sdk: flutter
  lint: 2.3.0
  riverpod_generator: 2.6.3
  riverpod_lint: 2.6.3

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/images/
    - assets/vectors/

# RPS
# Запуск — $ rps [script_name]
scripts:
  get: flutter pub get
  test: flutter test lib
  gen: dart run build_runner build --delete-conflicting-outputs
  watch: dart run build_runner watch
  assets: spider build
