name: Label issues
on:
  issues:
    types:
      - reopened
      - opened

jobs:
  label_issues:
    uses: surfstudio/flutter-ci-workflows/.github/workflows/new_pull_request_label.yml@main
    secrets:
      SECRET_ISSUES: ${{ secrets.ACCESS_TOKEN }}
