name: Label issues
on:
  issues:
    types:
      - reopened
      - opened

jobs:
  label_issues:
    if: github.repository == 'martynov-alex/github_actions_examples'
    uses: martynov-alex/github_actions_examples/.github/workflows/new_issues_label.yml@main
    secrets:
      ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
